### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Orleans.Runtime.Logger.Error(Int32, System.String, System.Exception)

### ISSUE THREAD

**Issue by rosdi** [OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage#11]
Hi,

I am trying to use this with the latest Orleans `v1.3.0-beta1`. However I am getting this stacktrace whenever I try to start Orleans... is this versioning issue?

```
OrleansHost.exe Error: 0 : [2016-09-16 12:53:36.354 GMT    15   ERROR   103109  ProviderLoader/IStorageProvider 127.0.0.1:11111]    !!!!!!!!!! Exception initializing provider Name=PubSubStore Type=[PubSubStore, Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage]  
Exc level 0: System.MissingMethodException: Method not found: 'Void Orleans.Runtime.Logger.Error(Int32, System.String, System.Exception)'.
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.<Init>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.Init(String name, IProviderRuntime providerRuntime, IProviderConfiguration config)
   at Orleans.Providers.ProviderLoader1.<InitProviders>d__6.MoveNext() 

OrleansHost.exe Error: 0 : [2016-09-16 12:53:36.376 GMT     1   ERROR   100439  Silo    127.0.0.1:11111]    !!!!!!!!!! Exception during Silo.Start  
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
Exc level 1: System.MissingMethodException: Method not found: 'Void Orleans.Runtime.Logger.Error(Int32, System.String, System.Exception)'.
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.<Init>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.Init(String name, IProviderRuntime providerRuntime, IProviderConfiguration config)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by amccool** [comment]
I assume you are using the nuget package.  The stable package is linked to the 1.2.x release.   

Here is a nuget package linked to 1.3.0-beta1.
https://ci.appveyor.com/api/buildjobs/to34ikblh7mrg28d/artifacts/Orleans.StorageProviders.SimpleSQLServerStorage.1.2.77-ffxxhxjd.nupkg.

**Comment by rosdi** [comment]
Yes I was using nuget package... I will try out the latest nuget beta once I can get back to it... cheers...

**Comment by amccool** [comment]
going to close this as is regarding the beta
