### ISSUE TITLE
EF issue during high sql server load

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage#15]
[2017-04-07 21:07:27.448 GMT    19	ERROR  	400111	StorageProvider.SimpleSQLServerStorage.00000000-0000-0000-0000-000000000000	172.18.124.52:11111]	!!!!!!!!!! Error reading: GrainType=CSNtfy.SipDialogInstance Grainid=GrainReference:*grn/15152CBD/611ffd8a ETag= from DataSource=SERVER.DefaultStorage	
Exc level 0: System.InvalidOperationException: The default DbConfiguration instance was used by the Entity Framework before the 'KeyValueDbConfiguration' type was discovered. An instance of 'KeyValueDbConfiguration' must be set at application start before using any Entity Framework features or must be registered in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=260883 for more information.
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForAssembly(Assembly assemblyHint, Type contextTypeHint)
   at System.Data.Entity.DbContext.InitializeLazyInternalContext(IInternalConnection internalConnection, DbCompiledModel model)
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.<ReadStateAsync>d__16.MoveNext()

**Comment by amccool** [comment]
so far so good with this PR, I will let it run another day, then close if we dont see any issues

**Comment by amccool** [comment]
so far so good
