### ISSUE TITLE
When Clear is called, sometimes the delete failed with `affected an unexpected number of rows (0)`

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage#22]
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0)

Error from storage provider during ClearState for grain Type=Orleans.Streams.PubSubRendezvousGrain Pk=*grn/716E8E94/0000000000000000590000000000000006000000716e8e94+BedStreamProvider_BedEvent-22-0x277E9B6A Id=GrainReference:*grn/716E8E94/00000000+BedStreamProvider_BedEvent-22 Error=
 
Exc level 0: System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage.<ClearStateAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<ClearStateAsync>d__8.MoveNext()
Exc level 1: System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.

**Comment by amccool** [comment]
since we want to clear to complete, and the rows are 0, we can log this error and continue

**Comment by jeoffman** [comment]
smells like an un-awaited task
